"""Exercise the HA adapter without connecting to an ARC on the network.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from types import SimpleNamespace
from unittest.mock import AsyncMock, Mock, patch

from custom_components.dahua_arc import (
    async_migrate_entry,
    async_setup_entry,
    async_unload_entry,
)
from custom_components.dahua_arc.api import Zone
from custom_components.dahua_arc.const import CONF_ARC_SERIAL, DOMAIN
from custom_components.dahua_arc.diagnostics import async_get_config_entry_diagnostics
from homeassistant.const import CONF_HOST, CONF_PASSWORD, CONF_USERNAME
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr
from pytest_homeassistant_custom_component.common import MockConfigEntry


def _fake_hub() -> SimpleNamespace:
    zone = Zone(
        index=7,
        name="Kitchen Window",
        classification="multiio_input",
        is_multiio=True,
        level1=2,
        level2=1,
    )
    return SimpleNamespace(
        host="192.0.2.10",
        serial_number="ARC-TEST-001",
        device_type="ARC3800",
        software_version="test",
        enable_research_features=False,
        radio_devices={},
        parents={2: {"name": "MultiIO board 2"}},
        primary_zones={7: zone},
        inventory_error=None,
        start=Mock(),
        stop=Mock(),
        diagnostics=Mock(return_value={"connected": True}),
    )


async def test_setup_unload_preserves_legacy_identity(hass: HomeAssistant) -> None:
    entry = MockConfigEntry(
        domain=DOMAIN,
        unique_id="192.0.2.10:5000",
        data={
            CONF_HOST: "192.0.2.10",
            CONF_USERNAME: "admin",
            CONF_PASSWORD: "test-only",
        },
        version=4,
    )
    entry.add_to_hass(hass)
    hub = _fake_hub()
    with (
        patch("custom_components.dahua_arc.ArcHub", return_value=hub),
        patch.object(
            hass.config_entries, "async_forward_entry_setups", new_callable=AsyncMock
        ) as forward,
        patch.object(
            hass.config_entries,
            "async_unload_platforms",
            new_callable=AsyncMock,
            return_value=True,
        ) as unload,
    ):
        assert await async_migrate_entry(hass, entry) is True
        assert entry.version == 5
        assert await async_setup_entry(hass, entry) is True
        assert entry.unique_id == "192.0.2.10:5000"
        assert entry.data[CONF_ARC_SERIAL] == "ARC-TEST-001"
        assert entry.runtime_data is hub
        assert forward.await_count == 1
        registry = dr.async_get(hass)
        assert (
            registry.async_get_device_by_identifier(
                (DOMAIN, "192.0.2.10:5000"), entry.entry_id
            )
            is not None
        )
        assert (
            registry.async_get(hub.child_device_ids[7]).parent_device_id
            == (hub.multiio_parent_ids[2])
        )
        assert await async_unload_entry(hass, entry) is True
        unload.assert_awaited_once()
    hub.start.assert_called_once()
    hub.stop.assert_called_once()


async def test_diagnostics_redacts_connection_identity(hass: HomeAssistant) -> None:
    entry = MockConfigEntry(
        domain=DOMAIN,
        data={
            CONF_HOST: "192.0.2.10",
            CONF_USERNAME: "admin",
            CONF_PASSWORD: "test-only",
            CONF_ARC_SERIAL: "ARC-TEST-001",
        },
    )
    entry.add_to_hass(hass)
    entry.runtime_data = _fake_hub()
    result = await async_get_config_entry_diagnostics(hass, entry)
    assert "192.0.2.10" not in str(result["entry"])
    assert "admin" not in str(result["entry"])
    assert "test-only" not in str(result["entry"])
    assert "ARC-TEST-001" not in str(result["entry"])
    assert result["runtime"] == {"connected": True}
