"""Validate the minimal installable Home Assistant archive contents.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

ROOT = Path(__file__).resolve().parents[1]
COMPONENT = ROOT / "custom_components" / "dahua_arc"
ALLOWED = {".py", ".json", ".png", ".md"}
REQUIRED = {
    "custom_components/dahua_arc/__init__.py",
    "custom_components/dahua_arc/manifest.json",
    "custom_components/dahua_arc/translations/en.json",
    "custom_components/dahua_arc/brand/icon.png",
    "custom_components/dahua_arc/vendor/LICENSE-python-dhip",
    "README.md",
    "LICENSE",
    "SECURITY.md",
}


def package_paths() -> list[Path]:
    """Select only installable component files and human-readable notices."""
    files = [
        path
        for path in COMPONENT.rglob("*")
        if path.is_file()
        and (path.suffix in ALLOWED or path.name == "LICENSE-python-dhip")
    ]
    return sorted([*files, ROOT / "README.md", ROOT / "LICENSE", ROOT / "SECURITY.md"])


def build_archive(path: Path) -> None:
    """Build an archive whose top-level path is custom_components/."""
    with ZipFile(path, "w", compression=ZIP_DEFLATED) as archive:
        for source in package_paths():
            archive.write(source, source.relative_to(ROOT).as_posix())


def main() -> None:
    manifest = json.loads((COMPONENT / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["version"] == "0.6.0"
    assert not (COMPONENT / "strings.json").exists()
    assert not (COMPONENT / "alarm_control_panel.py").exists()
    with tempfile.TemporaryDirectory() as temporary:
        archive_path = Path(temporary) / "dahua_arc_ha_v0.6.0.zip"
        build_archive(archive_path)
        with ZipFile(archive_path) as archive:
            names = set(archive.namelist())
            assert REQUIRED <= names, sorted(REQUIRED - names)
            assert all("__pycache__" not in name for name in names)
            assert all("bootstrap" not in name for name in names)
            assert all("capture" not in name for name in names)
            assert all(
                name.startswith("custom_components/dahua_arc/")
                or name in {"README.md", "LICENSE", "SECURITY.md"}
                for name in names
            )
    print(f"Package integrity OK: {len(names)} files")


if __name__ == "__main__":
    main()
